### ISSUE TITLE
Application doesn't show my published/unpublished stories

### ISSUE THREAD

**Issue by snowman10** [TryGhost/Ghost-Android#11]
FILL THESE DETAILS FIRST:

- Ghost version: 1.20.0
- App version: 1.0.0

----

DESCRIBE YOUR ISSUE HERE

Hello, my web contains two users for two physical people. When I use Android application  I can see just only drafts of second user. Neither my published or unpublished texts. I attached content of DB table users. My user is starting with D.... letter.

Thank you for help

![2018-01-17 11_54_27-db browser for sqlite - c__ftp_ghost_content_data_ghost-local db](https://user-images.githubusercontent.com/35526019/35039807-4780149c-fb7f-11e7-942c-8639dbbc3cc3.png)

**Comment by vickychijwani** [comment]
Hello @snowman10! 👋

What is the "role" of each of these users? Owner / admin / editor / author?

**Comment by snowman10** [comment]
Hello, both users are "Authors" and Admin is "Owner"
