### ISSUE TITLE
Migrate open issues?! 

### ISSUE THREAD

**Issue by Memphizzz** [TryGhost/Ghost-Android#12]
How is it that a deal breaker like this issue from 2015(!!!) is not yet fixed or at least migrated to this repo?
https://github.com/vickychijwani/quill/issues/81
The whole app is useless to anyone who has more than 29 drafts...

This is more than just disappointing.

**Comment by ErisDS** [comment]
Please read our [code of conduct](https://ghost.org/conduct/) before posting anything further to our community.
