### ISSUE TITLE
Use Image Viewer for selection of Upload Image

### ISSUE THREAD

**Issue by realthargor** [TryGhost/Ghost-Android#17]
Currently an internal file selection dialog opens when selecting an image to upload. This is cumbersome because this dialog doesn't have the ordering mode "date taken", can't order asc or desc and doesn't remember the last selected order mode.

Would be nice if a more gallery like dialog/app would open. Like Simple Gallery
 (A gallery for viewing photos and videos without ads.
) - https://f-droid.org/app/com.simplemobiletools.gallery

**Comment by vickychijwani** [comment]
Hey @realthargor. Actually, it opens whatever image picker dialog your manufacturer has set as the default on your phone ([code](https://github.com/TryGhost/Ghost-Android/blob/9a54a14836e6526ff69649699fbea88e4b2a7228/app/src/main/java/me/vickychijwani/spectre/view/fragments/PostEditFragment.java#L415-L417)). The image picker on Google's version of Android does have a way to sort by ascending/descending order of time:

<img width="300" src="https://user-images.githubusercontent.com/439616/36348675-30212a7c-149b-11e8-9ba1-9ec6aa14b632.jpg" />

Closing, as there isn't much I can do here short of implementing a custom image picker, for which the cost-benefit doesn't work out.

**Comment by realthargor** [comment]
Hi @vickychijwani
thanks for the answer.
I looked at it a bit myself. Would it not be okay to use a imagepicker library or just use another intend like this:
Intent galleryIntent = new Intent(Intent.ACTION_PICK,	             android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI);    startActivityForResult(galleryIntent, RESULT_LOAD_IMG);
30
	    }

Or is that what you mean by implementing a custom image picker?

**Comment by vickychijwani** [comment]
So, the piece of code you have will work only for the gallery and some apps - it won't work correctly for picking images from Dropbox, Google Photos, and/or other apps that expose their content in the image picker and download it on-demand.

I'm also not inclined to use a library as this (picking images) is a first-class concept on Android by default, so the default picker is likely to be better integrated with the rest of the system and likely to work better overall.

**Comment by realthargor** [comment]
Makes sense. Thanks for explaining, I learned a lot. :)
