### ISSUE TITLE
Integration of Speech-to-text

### ISSUE THREAD

**Issue by jochenkirstaetter** [TryGhost/Ghost-Android#2]
Given the deployment to mobile and tablet devices running on Android it would be great to have the ability to use speech-to-text feature. This way, it would be possible to dictate your blog posts rather than typing them.

Eventually, this could be a keyboard-related feature on Android but surely an interesting addition to the pure Markdown based editor.

What's your opinion on that?

Regards, JoKi

**Comment by vickychijwani** [comment]
Hi @jochenkirstaetter 👋

This is a keyboard feature and _already_ possible to use by enabling it in your phone settings > Languages and Input > Google Voice Typing (might vary depending on your phone manufacturer).

**Comment by jochenkirstaetter** [comment]
Hi @vickychijwani 

Thanks for clarification. I wasn't sure whether it's a built-in feature of the keyboard or not. Even better than.
