### ISSUE TITLE
Support for multiple blogs

### ISSUE THREAD

**Issue by jlelse** [TryGhost/Ghost-Android#23]
This is more of a feature request, than a bug: Is it possible to add support for multiple blogs without the need to logout from one to login to another? I currently have 3 blogs using Ghost.

**Comment by vickychijwani** [comment]
Hi @jlelse! :wave: There is already an open issue for this (#13), so I'm going to close this one.

**Comment by jlelse** [comment]
Sorry, I must have missed this.
