### ISSUE TITLE
1Password can't fill in credentials

### ISSUE THREAD

**Issue by jessehouwing** [TryGhost/Ghost-Android#27]
FILL THESE DETAILS FIRST:

- Ghost version: ghost.io
- App version: 1.1.3

----
I use 1Password as my password manager. When I try to log on the following sequence happens:

 1. Enter url; I enter my blog url
 2. Enter username & password; I ask 1Password to fill these in for me
 3. 1Password prompts for my fingerprint; I supply it
 4. App goes back to the "enter url" screen and 1password is dismissed
 5. Goto 1

Very annoying ;).

**Comment by vickychijwani** [comment]
Thanks for catching this!
