### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by KopfKrieg** [TryGhost/Ghost-Android#32]
As an alternative to the Google Play Store it would be nice to have the App published on [F-Droid](https://f-droid.org) too.

**Comment by vickychijwani** [comment]
Hi @KopfKrieg :wave:

Sorry, I'm going to close this. F-Droid doesn't have enough users to justify putting in effort on this, honestly. We also use proprietary libraries like Crashlytics and Google Play Services that are incompatible with F-Droid's [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/).

**Comment by Efreak** [comment]
Any chance you'll add this, @IzzySoft

**Comment by IzzySoft** [comment]
@Efreak Nope. First, there are no APKs attached to the releases, and second:

> We also use proprietary libraries like Crashlytics and Google Play Services

To paraphrase Vicky: "The FOSS community hasn't enough users accepting those proprietary components to justify putting effort on this". Nothing I can do here, sorry.
