### ISSUE TITLE
No access to development http sites

### ISSUE THREAD

**Issue by mlawren** [TryGhost/Ghost-Android#33]
- Ghost version: X.Y.Z
- App version: 1.2.1
----

The app interface, on the first screen, strictly enforces a https address. This prevents access to a local Ghost instance running in development mode. It would be nice to have a checkbox or some other mechanism to allow that.

**Comment by vickychijwani** [comment]
Hi @mlawren! :wave:

Even though the login screen says `https`, it will fall back to `http` if that doesn't work. Try it 🙂

**Comment by mlawren** [comment]
Hi Vicky,

> Even though the login screen says `https`, it will fall back to
> `http` if that doesn't work. Try it :slightly_smiling:

Thanks for the quick response. Happy to hear that I can in fact connect
to http sites.

I agree that this issue can be closed but I still think there is a
useability issue. The interface makes it clear that http is not even an
option. It would be less confusing if the prompt didn't mention a
protocol at all. Perhaps consider removing it?

Thanks for all your hard work making this app!

-- 
Mark Lawrence
