### ISSUE TITLE
Cursor moves to a new location randomly sometimes

### ISSUE THREAD

**Issue by fallerOfFalls** [TryGhost/Ghost-Android#37]
Ghost version: 1.24.4
App version: 1.2.1
Device: Nexus 5
Android version: 7.1.2 (Lineage OS)

I struggle to find any pattern in this, other than, it happens when I'm using backspace. Instead of deleting the text I just wrote, the cursor is somewhere higher up, deleting something else until i notice, take my finger off the backspace and then try to remember what had been mistakenly deleted.

**Comment by fallerOfFalls** [comment]
This just happened in Telegram, so I'm guessing it's not an issue with the ghost app. No idea why it happens so often with ghost app specifically.

**Comment by vickychijwani** [comment]
Hey @fallerOfFalls - thanks for following up on this. Yes, we're using the standard Android EditText widget without any additional tricks, so I doubt this is a Ghost Android issue. Nevertheless if you find a reliable way to reproduce this, feel free to reopen.
