### ISSUE TITLE
Uploaded images are not rotated correctly on Galaxy S7

### ISSUE THREAD

**Issue by mangefox** [TryGhost/Ghost-Android#4]
When picking and uploading images from Samsung Galaxy S7, portrait images are not added with the correct orientation. I tested with a Pixel and there it's working correctly. 

SO post talking about same/similar issue: https://stackoverflow.com/questions/40258153/choosing-images-on-a-samsung-galaxy-device-rotates

- Ghost version: 1.17.3
- App version: 1.0.0

**Comment by mangefox** [comment]
This thread seems to offer context and a solution:

https://stackoverflow.com/questions/39400351/android-exif-data-always-0-how-to-change-it

**Comment by vickychijwani** [comment]
Hi @mangefox 👋

Could you add a screenshot demonstrating the issue? That would help, especially since I don't have a Samsung device to test with.

**Comment by vickychijwani** [comment]
Actually nevermind, this looks like an upstream issue in Picasso: https://github.com/square/picasso/issues/691

**Comment by mangefox** [comment]
I'll add this screenshot anyway: https://i.imgur.com/3dl3Vbo.jpg

Both images appear correctly rotated in the gallery (when picking) but not once imported into the Ghost app. When viewing image details in the gallery app, it correctly identifies one with 0° rotation and the other with 90° rotation. I guess that information gets lost somewhere or not taken into account.

**Comment by AileenCGN** [comment]
@vickychijwani Probably related to issues we collected in https://github.com/TryGhost/Ghost/issues/4453

**Comment by vickychijwani** [comment]
Thanks Aileen! The links in that issue are quite helpful, especially https://github.com/TryGhost/Ghost/issues/1688

**Comment by mangefox** [comment]
@vickychijwani If you want help with testing I'd gladly help

**Comment by vickychijwani** [comment]
I tried to see if some of the related PRs upstream (https://github.com/square/picasso/pull/1021, https://github.com/square/picasso/pull/1031, https://github.com/square/picasso/pull/1032) could fix this, but so far it seems they don't actually help. Test images were taken from [here](https://github.com/recurser/exif-orientation-examples) - none of the possible EXIF orientations are handled correctly, at least in landscape.

@mangefox could you share a portrait and a landscape image taken directly from your Samsung S7 camera? Maybe we'll get a different result with that, atlhough I'm not too hopeful.

**Comment by mangefox** [comment]
Here you go. Added photos from my Pixel also (which get orientated correctly)

[photos.zip](https://github.com/TryGhost/Ghost-Android/files/1713330/photos.zip)

**Comment by vickychijwani** [comment]
I realized I was making a mistake during testing earlier: I was looking at images in the post preview, which is rendered by Chrome, so a fix for Picasso can't help with that anyway 🤦‍

Additionally, since Ghost is affected by the same issue, it wouldn't make sense to fix this in Ghost Android's preview pane - the preview wouldn't match what you see on your blog. I'm going to close this for now and potentially revisit when there's some change in the corresponding Ghost issue (linked above).
