### ISSUE TITLE
[Feature request] A Ghost-Android SDK

### ISSUE THREAD

**Issue by bizzbyster** [TryGhost/Ghost-Android#40]
It would be great if I could integrate Ghost-Android into my own Kotlin app. Is this something that is already pretty easy to do? Or? Thoughts?

**Comment by vickychijwani** [comment]
Hi @bizzbyster 👋

Ghost Android is an app for end-users, not a library for developers. So the term "SDK" does not apply in this context. I'm also not sure what you mean by "integrate Ghost-Android into my own Kotlin app".

Hopefully that clears up the confusion. Feel free to comment further if I've misunderstood.
