### ISSUE TITLE
Add new feature : Password on page

### ISSUE THREAD

**Issue by SckyzO** [TryGhost/Ghost-Android#44]
Hello World, 

I would like to request a new feature.
It is possible to add a login/password (or just password) for a page (or page and post)

Regards,

**Comment by SckyzO** [comment]
Hello, 
Why close without explication ? 

Best Regard,

**Comment by vickychijwani** [comment]
@SckyzO this a feature request for Ghost in general, not for Ghost Android (which is just the mobile app).

**Comment by SckyzO** [comment]
Ho Sorry :)

Thx :)
