### ISSUE TITLE
Following 'view on blog' goes to wrong post if slug was already taken

### ISSUE THREAD

**Issue by mangefox** [TryGhost/Ghost-Android#5]
- Ghost version: 1.17.3
- App version: 1.0.0

----

The app presumes that the slug name is not occupied, so the "view post on blog" button after publishing naïvely goes to http://blog/presumed-slug. If the presumed slug is already taken by an older blog post, you are taken to the old post.

**Comment by vickychijwani** [comment]
@mangefox Thanks for reporting the issue! Fixed 👍
