### ISSUE TITLE
Chinese translation needs to be corrected in many places

### ISSUE THREAD

**Issue by jijichat** [TryGhost/Ghost-Android#6]
Hello,Chinese translation needs to be corrected in many places, the new features and important parts of many Ghost blogs, there is no correct translation or no translation in Chinese, and the request is corrected!

**Comment by vickychijwani** [comment]
Hi @jijichat 👋

Ghost Android relies on the user community for translations. If you're interested in helping out by adding/correcting translations, please see the translation project on [Weblate](https://hosted.weblate.org/engage/ghost/en/).

Closing this issue as there's nothing actionable for me here.
